exp_name: 'base_res224_lr1x_res32_encoder-1e-5_layer-2-0-4_volume-2.0_iter20k_pretrain-omniobj_world-coord_no-emb'
exp_group: 'leap-dtu'
output_dir: './output/'
log_dir: './log'
workers: 4
print_freq: 50
vis_freq: 500
eval_vis_freq: 10
seed: 42

# dataset config
dataset:
  name: 'dtu'
  category: 'general'
  task: 'singlesequence'
  img_size: 224
  img_size_height: 168
  img_size_render: 112
  num_frame: 5
  mask_images: True
  train_all_frame: False
  augmentation: False
  aug_brightness: 0.3
  aug_contrast: 0.3
  aug_saturation: 0.3
  aug_hue: 0.1

# network config
model:
  norm_first: False
  # backbone
  backbone_name: 'dinov2'
  backbone_type: 'vitb14'
  backbone_fix: False
  backbone_out_dim: 768
  # encoder
  encoder_layers: 2
  # pe transformer
  use_neck: False
  neck_scale: 'constant_1' #'channel' #'constant_1'
  neck_layers: 2
  pe_with_spatial_pe: False
  # lifting
  lifting_TXdecoder_permute: False
  use_pe_lifting: False
  lifting_use_conv3d: False
  lifting_layers: 4
  latent_res: 16
  # rendering
  volume_res: 64
  render_feat_dim: 16
  render_feat_raw: False
  # others
  rot_representation: 'quat'
  use_flash_attn: False

# render config
render:
  n_pts_per_ray: 64
  volume_size: 2.0 #2.0  # 1.2
  min_depth: 1.2 #1.2  # 0.7
  max_depth: 4.2 #4.2  # 3.5
  camera_z: 2.0 # camera pose T_z, range [1.5, 2.2]
  k_size: 5

# loss config
loss:
  weight_render_rgb: 1.0
  weight_render_mask: 0.0 #5.0
  weight_perceptual: 0 #.0
  iter_perceptual: 0 #10000
  weight_feat_render: 0.0

# training config
train:
  resume: False
  lr: 0.0001
  lr_embeddings: 0.0001
  lr_backbone: 0.00001  # 0.00002
  weight_decay: 0.005
  schedular_warmup_iter: 500
  total_iteration: 200000 #200000
  batch_size: 4
  accumulation_step: 1
  normalize_img: True
  grad_max: 5.0
  use_amp: False
  use_rand_view: False
  min_rand_view: 3
  use_uncanonicalized_pose: True
  #pretrain_path: 'output/kubric/train_224/base_res224_lr2x_percploss-0.1_res32_encoder-nonfix-1e-5_no-neck_no-feat-render-loss/cpt_best_psnr_27.224168484870876.pth.tar'
  pretrain_path: 'output/omniobject3d/train_224/base_res224_lr2x_percploss-0.1_res32_encoder-nonfix-1e-5_layer-2-0-4_volume-2_rel-pose/cpt_best_psnr_29.21728228794307.pth.tar'

# test config
test:
  batch_size: 1
  compute_metric: True
